apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata: 
  namespace: dev 
  name: dev-binding 
subjects: 
  - kind: User  
    name: dev-user 
roleRef: 
  kind: Role 
  name: dev-role 
  apiGroup: rbac.authorization.k8s.io